### ISSUE TITLE
Online or Offline tool ?

### ISSUE THREAD

**Issue by ENLYOWH** [TorniX0/OpenTimerResolution#4]
hi there,
i have a question for you about OpenTimerResolution, is it an online or offline working tool ?
Indeed, this report : https://www.virustotal.com/gui/file/6faea56ff845b9c0afc1b7cc94589fbc72f3fac5d40d309ed1e839b4adb0c651/relations shows that your progam connects to 10 domains and  13 ip addresses.
Cordially

**Comment by TorniX0** [comment]
The only connection to the internet that OpenTimerResolution has is the GitHub page itself to check for updates (check out the source code).
Those connections you've shown me from VirusTotal seem to be from Microsoft, so it's most likely the .NET library redirecting you to download the runtime.

![netruntime](https://user-images.githubusercontent.com/43686655/197856491-2cf4ae90-36ee-40e8-8b76-b99ebd8fc1f4.PNG)
