### ISSUE TITLE
When does it purge cache memory?

### ISSUE THREAD

**Issue by ghost** [TorniX0/OpenTimerResolution#6]
I wonder when does it that automatically when selected?

**Comment by TorniX0** [comment]
> I wonder when does it that automatically when selected?

The application purges the standby cache under the following conditions:
+ The standby cache must be over or equal to 2048MB
+ The available free memory must be lower than the total memory divided by 2

(**https://github.com/TorniX0/OpenTimerResolution/blob/da18943388867f94ee2bbb3ead9b645bc07674ec/src/MainWindow.cs#L495C12-L495C12**)
